//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Heroes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Heroe
    {
        public int IdHeroe { get; set; }
        public string Nombre { get; set; }
        public string Historia { get; set; }
        public string Poder { get; set; }
        public string Debilidad { get; set; }
        public string Universo { get; set; }
        public string Imagen { get; set; }
    }
}
